AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 bucket for example pipeline

Resources:
  ExampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub example-pipeline-bucket-${AWS::AccountId}-${AWS::Region}

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref ExampleBucket